[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.35"

[[constraint]]
  branch = "master"
  name = "github.com/banzaicloud/hollowtrees"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"